# Generated by Django 5.1.6 on 2025-02-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('technical_specs_doc', models.FileField(blank=True, null=True, upload_to='pilot_specs/')),
                ('performance_metrics', models.TextField(blank=True, null=True)),
                ('compliance_requirements', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='organizations.organization')),
                ('pilot_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pilots', to='organizations.pilotdefinition')),
            ],
        ),
    ]
