# Generated by Django 4.2.20 on 2025-04-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('technical_specs_doc', models.FileField(blank=True, null=True, upload_to='pilot_specs/')),
                ('performance_metrics', models.TextField(blank=True, null=True)),
                ('compliance_requirements', models.TextField(blank=True, help_text='Specify the definition of done for this pilot', null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Enter the fixed price for this pilot (in USD)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_consumed', models.BooleanField(default=False, help_text='Whether a token was consumed for this pilot')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the pilot was published', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='organizations.organization')),
                ('pilot_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pilots', to='organizations.pilotdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PilotBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Transaction fee percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pilots.pilot')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='organizations.organization')),
            ],
            options={
                'unique_together': {('pilot', 'startup')},
            },
        ),
    ]
