# Generated by Django 5.1.6 on 2025-02-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'type': 'enterprise'}, on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='organizations.organization'),
        ),
    ]
