# Generated by Django 5.1.6 on 2025-02-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_primary_contact_email'),
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('range', 'Price Range'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20),
        ),
        migrations.CreateModel(
            name='PilotBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pilots.pilot')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='organizations.organization')),
            ],
            options={
                'unique_together': {('pilot', 'startup')},
            },
        ),
    ]
