# Generated by Django 4.2.20 on 2025-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotbid',
            name='enterprise_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text="Enterprise's portion of transaction fee", max_digits=5),
        ),
        migrations.AddField(
            model_name='pilotbid',
            name='startup_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text="Startup's portion of transaction fee", max_digits=5),
        ),
        migrations.AlterField(
            model_name='pilotbid',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Total transaction fee percentage', max_digits=5),
        ),
    ]
