# Generated by Django 5.2 on 2025-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0002_pilotbid_enterprise_fee_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='token_consumed',
        ),
        migrations.AlterField(
            model_name='pilot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Enter the fixed price for this pilot (in USD)', max_digits=10),
        ),
    ]
