# Generated by Django 5.1.6 on 2025-02-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_pilotdefinition_description'),
        ('pilots', '0002_alter_pilot_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='compliance_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pilot',
            name='performance_metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='pilot_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pilots', to='organizations.pilotdefinition'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='technical_specs_doc',
            field=models.FileField(blank=True, null=True, upload_to='pilot_specs/'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='organizations.organization'),
        ),
    ]
