# Generated by Django 5.2 on 2025-05-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0003_remove_pilot_token_consumed_alter_pilot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotbid',
            name='enterprise_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Enterprise's portion of transaction fee", max_digits=5),
        ),
        migrations.AlterField(
            model_name='pilotbid',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Total transaction fee percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pilotbid',
            name='startup_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Startup's portion of transaction fee", max_digits=5),
        ),
    ]
