# Generated by Django 5.2.1 on 2025-05-13 23:58

import apps.pilots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0004_update_fee_percentages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='compliance_requirements_doc',
            field=models.FileField(blank=True, null=True, upload_to=apps.pilots.models.pilot_compliance_doc_path),
        ),
        migrations.AddField(
            model_name='pilot',
            name='performance_metrics_doc',
            field=models.FileField(blank=True, null=True, upload_to=apps.pilots.models.pilot_performance_doc_path),
        ),
        migrations.AddField(
            model_name='pilot',
            name='technical_specs_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='technical_specs_doc',
            field=models.FileField(blank=True, null=True, upload_to=apps.pilots.models.pilot_technical_doc_path),
        ),
    ]
