# Generated by Django 5.1.6 on 2025-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0004_pilotbid_fee_percentage_alter_pilotbid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the pilot was published', null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='token_consumed',
            field=models.BooleanField(default=False, help_text='Whether a token was consumed for this pilot'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='compliance_requirements',
            field=models.TextField(blank=True, help_text='Specify the definition of done for this pilot', null=True),
        ),
    ]
