# Generated by Django 5.2.1 on 2025-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0007_alter_pilotbid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotbid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('live', 'Live'), ('declined', 'Declined'), ('completion_pending', 'Completion Pending'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
