# Generated by Django 5.2.1 on 2025-06-05 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0009_pilotbid_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotbid',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection provided by enterprise', null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Enter the fixed price for this pilot (in USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(1000.0, message='Pilot price must be at least $1,000')]),
        ),
    ]
