# Generated by Django 5.2.1 on 2025-06-24 17:42

import apps.pilots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0010_pilotbid_rejection_reason_alter_pilot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotbid',
            name='proposal_doc',
            field=models.FileField(blank=True, help_text='Optional: Upload a document to supplement your proposal', null=True, upload_to=apps.pilots.models.pilot_bid_doc_path),
        ),
    ]
