# Generated by Django 5.2.1 on 2025-06-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0011_pilotbid_proposal_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='admin_verified_at',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='admin_verified_by',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='verified',
        ),
    ]
