# Generated by Django 5.2.1 on 2025-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0012_remove_pilot_admin_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='featured_order',
            field=models.PositiveIntegerField(default=999, help_text='Order for featured sections (lower numbers appear first, 0 = highest priority)'),
        ),
    ]
