# Generated by Django 4.2.20 on 2025-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpackage',
            name='token_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
