# Generated by Django 5.1.6 on 2025-04-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_create_token_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenpackage',
            options={'ordering': ['price_per_token']},
        ),
        migrations.RenameField(
            model_name='tokenpackage',
            old_name='price',
            new_name='price_per_token',
        ),
        migrations.RemoveField(
            model_name='tokenpackage',
            name='token_count',
        ),
    ]
