# Generated by Django 4.2.20 on 2025-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_tokenpackage_token_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenpackage',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='tokenpackage',
            name='price_per_token',
        ),
        migrations.AddField(
            model_name='tokenpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
