# Generated by Django 5.1.6 on 2025-04-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_initialize_tokens'),
        ('payments', '0003_alter_tokenpackage_options_and_more'),
        ('pilots', '0005_add_token_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='pilot_limit',
            new_name='initial_tokens',
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('startup_monthly', 'Startup Monthly'), ('startup_yearly', 'Startup Yearly'), ('enterprise_monthly', 'Enterprise Monthly'), ('enterprise_yearly', 'Enterprise Yearly')], max_length=50),
        ),
        migrations.CreateModel(
            name='TokenConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_consumed', models.IntegerField(default=1)),
                ('action_type', models.CharField(choices=[('pilot_publish', 'Pilot Publication'), ('other', 'Other Consumption')], default='pilot_publish', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_consumption_logs', to='organizations.organization')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_consumptions', to='pilots.pilot')),
            ],
        ),
    ]
