# Generated by Django 4.2.20 on 2025-04-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pilots', '0002_pilotbid_enterprise_fee_percentage_and_more'),
        ('payments', '0003_alter_tokenpackage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseFeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='organizations.organization')),
                ('pilot_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_fee', to='pilots.pilotbid')),
            ],
        ),
    ]
