# Generated by Django 5.2 on 2025-05-02 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_enterprisefeetransaction'),
        ('pilots', '0002_pilotbid_enterprise_fee_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startup_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enterprise_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('startup_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('instructions_sent', 'Instructions Sent'), ('payment_initiated', 'Payment Initiated'), ('received', 'Received'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructions_sent_at', models.DateTimeField(blank=True, null=True)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('wire_transfer_date', models.DateField(blank=True, null=True)),
                ('wire_transfer_confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('startup_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('startup_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('startup_routing_number', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('pilot_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='pilots.pilotbid')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_payment_logs', to=settings.AUTH_USER_MODEL)),
                ('escrow_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.escrowpayment')),
            ],
        ),
    ]
