# Generated by Django 5.2 on 2025-05-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_escrow_payment_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterpriseFeeTransaction',
        ),
    ]
