# Generated by Django 5.2 on 2025-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_delete_enterprisefeetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='initial_tokens',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='pilot_limit',
            field=models.IntegerField(blank=True, help_text='Maximum number of published pilots allowed (null = unlimited)', null=True),
        ),
    ]
