# Generated by Django 5.2 on 2025-05-05 21:47

from django.db import migrations

def update_plan_limits(apps, schema_editor):
    PricingPlan = apps.get_model('payments', 'PricingPlan')
    
    # Set the limits for enterprise plans
    PricingPlan.objects.filter(plan_type='enterprise_monthly').update(pilot_limit=5)
    PricingPlan.objects.filter(plan_type='enterprise_yearly').update(pilot_limit=None)  # Unlimited
    
    # Set initial pilot counts
    Organization = apps.get_model('organizations', 'Organization')
    Pilot = apps.get_model('pilots', 'Pilot')
    
    for org in Organization.objects.filter(type='enterprise'):
        published_count = Pilot.objects.filter(
            organization=org,
            status='published'
        ).count()
        
        org.published_pilot_count = published_count
        org.save()

def reverse_func(apps, schema_editor):
    # Code for reversing the migration if needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_pricingplan_initial_tokens_and_more'),
        ('organizations', '0004_remove_organization_token_balance_and_more'),
        ('pilots', '0003_remove_pilot_token_consumed_alter_pilot_price'),
    ]

    operations = [
        migrations.RunPython(update_plan_limits, reverse_func),
    ]
