# Generated by Django 5.2 on 2025-05-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_update_plan_limits_and_pilot_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransaction',
            name='package',
        ),
        migrations.RemoveField(
            model_name='tokentransaction',
            name='organization',
        ),
        migrations.DeleteModel(
            name='TokenConsumptionLog',
        ),
        migrations.DeleteModel(
            name='TokenPackage',
        ),
        migrations.DeleteModel(
            name='TokenTransaction',
        ),
    ]
