# Generated by Django 5.2.1 on 2025-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_tokentransaction_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpayment',
            name='enterprise_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='startup_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
