# Generated by Django 5.2.1 on 2025-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_escrowpayment_enterprise_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowpaymentlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='startup_account_number',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='startup_bank_name',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='startup_routing_number',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='wire_transfer_confirmation',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='wire_transfer_date',
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='External payment reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Invoice Pending'), ('instructions_sent', 'Invoice Sent'), ('payment_initiated', 'Payment Initiated'), ('received', 'Payment Received'), ('released', 'Released to Startup'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
