# Generated by Django 5.2.1 on 2025-05-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_escrowpaymentlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Invoice Pending'), ('instructions_sent', 'Invoice Sent'), ('received', 'Payment Received & Work Active'), ('released', 'Released to Startup'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
