# Generated by Django 5.2.1 on 2025-06-26 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_escrowpayment_pilot_bid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('startup_monthly', 'Startup Monthly'), ('startup_yearly', 'Startup Yearly'), ('enterprise_monthly', 'Enterprise Monthly'), ('enterprise_yearly', 'Enterprise Yearly'), ('free_trial', 'Free Trial')], max_length=50),
        ),
        migrations.CreateModel(
            name='FreeAccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of this code')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(help_text='When this code expires')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of organizations that can use this code')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_free_account_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='free_account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.freeaccountcode'),
        ),
    ]
