# Generated by Django 5.2.1 on 2025-06-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_pricingplan_plan_type_freeaccountcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeaccountcode',
            name='free_months',
            field=models.PositiveIntegerField(default=12, help_text='Number of months of free access (default: 12)'),
        ),
        migrations.AddField(
            model_name='freeaccountcode',
            name='plan',
            field=models.ForeignKey(default=4, help_text='Which plan this code grants access to', on_delete=django.db.models.deletion.CASCADE, to='payments.pricingplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeaccountcode',
            name='valid_until',
            field=models.DateTimeField(help_text='When this code expires (redemption deadline)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('startup_monthly', 'Startup Monthly'), ('startup_yearly', 'Startup Yearly'), ('enterprise_monthly', 'Enterprise Monthly'), ('enterprise_yearly', 'Enterprise Yearly')], max_length=50),
        ),
    ]
