# Generated by Django 5.2.1 on 2025-06-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_freeaccountcode_free_months_freeaccountcode_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeaccountcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Free Account Code', 'verbose_name_plural': 'Free Account Codes'},
        ),
    ]
