# Generated by Django 5.2.1 on 2025-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_password_management_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this password reset is still valid/active'),
        ),
    ]
