# Generated by Django 4.2.20 on 2025-04-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('enterprise', 'Enterprise'), ('startup', 'Startup')], max_length=20)),
                ('website', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, choices=[('c_corp', 'C-Corporation'), ('s_corp', 'S-Corporation'), ('llc', 'LLC'), ('international', 'International')], max_length=20, null=True)),
                ('business_registration_number', models.CharField(blank=True, help_text='Format: country-code-number', max_length=50, null=True)),
                ('tax_identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Company description', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('primary_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('has_payment_method', models.BooleanField(default=False)),
                ('free_trial_used', models.BooleanField(default=False)),
                ('token_balance', models.IntegerField(default=0, help_text='Current number of available tokens')),
                ('tokens_used', models.IntegerField(default=0, help_text='Total number of tokens used')),
                ('tokens_purchased', models.IntegerField(default=0, help_text='Total number of tokens purchased')),
            ],
        ),
        migrations.CreateModel(
            name='PilotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Provide a detailed description of the pilot', null=True)),
                ('technical_specs_doc', models.FileField(blank=True, null=True, upload_to='pilot_specs/')),
                ('performance_metrics', models.TextField(blank=True, help_text='Define quantifiable performance metrics and KPIs', null=True)),
                ('compliance_requirements', models.TextField(blank=True, help_text='Specify explicit compliance requirements for production launch', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Make this pilot definition private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_definition', to='organizations.organization')),
            ],
        ),
    ]
