# Generated by Django 5.1.6 on 2025-02-17 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='domain',
        ),
        migrations.AddField(
            model_name='organization',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='Format: country-code-number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, choices=[('c_corp', 'C-Corporation'), ('s_corp', 'S-Corporation'), ('llc', 'LLC'), ('international', 'International')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(default='www.default.com', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PilotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_specs_doc', models.FileField(blank=True, null=True, upload_to='pilot_specs/')),
                ('performance_metrics', models.TextField(blank=True, help_text='Define quantifiable performance metrics and KPIs', null=True)),
                ('compliance_requirements', models.TextField(blank=True, help_text='Specify explicit compliance requirements for production launch', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Make this pilot definition private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_definition', to='organizations.organization')),
            ],
        ),
    ]
