# Generated by Django 5.1.6 on 2025-02-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='primary_contact_email',
        ),
    ]
