# Generated by Django 5.2 on 2025-05-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_bank_info_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bank_address',
        ),
    ]
