# Generated by Django 5.1.6 on 2025-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_primary_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='free_trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_payment_method',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
