# Generated by Django 5.1.6 on 2025-02-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotdefinition',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a detailed description of the pilot', null=True),
        ),
    ]
