# Generated by Django 5.1.6 on 2025-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_free_trial_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Company description', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='token_balance',
            field=models.IntegerField(default=0, help_text='Current number of available tokens'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tokens_purchased',
            field=models.IntegerField(default=0, help_text='Total number of tokens purchased'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Total number of tokens used'),
        ),
    ]
