# Generated by Django 5.1.6 on 2025-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_pilotdefinition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
