# Generated by Django 5.2 on 2025-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_bank_info_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='token_balance',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tokens_purchased',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tokens_used',
        ),
        migrations.AddField(
            model_name='organization',
            name='published_pilot_count',
            field=models.IntegerField(default=0, help_text='Number of published pilots'),
        ),
    ]
