# Generated by Django 5.2.1 on 2025-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_token_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.CharField(blank=True, default='+1', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, choices=[('', 'Select One'), ('c_corp', 'C-Corporation'), ('s_corp', 'S-Corporation'), ('llc', 'LLC'), ('international', 'International')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
