# Generated by Django 5.2.1 on 2025-06-09 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('', 'Select employee count'), ('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], help_text='Number of employees in your organization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_year',
            field=models.IntegerField(blank=True, help_text='Year the company was founded', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters_location',
            field=models.CharField(blank=True, help_text='City, State/Country where your headquarters is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
        migrations.CreateModel(
            name='PartnerPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the promotion or partnership', max_length=100)),
                ('description', models.TextField(help_text='Brief description of the promotion or partnership', max_length=500)),
                ('link_url', models.URLField(help_text='URL link for the promotion')),
                ('is_affiliate', models.BooleanField(default=False, help_text='Check if this is an affiliate link')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promotion is currently active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this promotion appears (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_promotions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Partner Promotion',
                'verbose_name_plural': 'Partner Promotions',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
