# Generated by Django 5.2.1 on 2025-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_employee_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpromotion',
            name='is_affiliate',
        ),
        migrations.AddField(
            model_name='partnerpromotion',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Mark as exclusive to the Fend network'),
        ),
        migrations.AlterField(
            model_name='partnerpromotion',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this deal offers', max_length=500),
        ),
        migrations.AlterField(
            model_name='partnerpromotion',
            name='link_url',
            field=models.URLField(help_text='URL where visitors can learn more or access the offer'),
        ),
        migrations.AlterField(
            model_name='partnerpromotion',
            name='title',
            field=models.CharField(help_text='Title of the exclusive offer or partnership', max_length=100),
        ),
    ]
