# Generated by Django 5.2.1 on 2025-07-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_logo_added', models.BooleanField(default=False)),
                ('profile_description_added', models.BooleanField(default=False)),
                ('team_members_added', models.BooleanField(default=False)),
                ('first_pilot_posted', models.BooleanField(default=False)),
                ('first_bid_made', models.BooleanField(default=False)),
                ('first_connection_made', models.BooleanField(default=False)),
                ('tags_added', models.BooleanField(default=False)),
                ('case_studies_added', models.BooleanField(default=False)),
                ('dismissed_suggestions', models.JSONField(blank=True, default=list)),
                ('onboarding_disabled', models.BooleanField(default=False, help_text='User chose to disable all onboarding suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Onboarding Progress',
                'verbose_name_plural': 'User Onboarding Progress',
                'db_table': 'organizations_user_onboarding_progress',
            },
        ),
    ]
