# Generated by Django 5.2.1 on 2025-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_useronboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='industry_tags',
            field=models.JSONField(blank=True, default=list, help_text="Industry tags for better matching (e.g., ['AI/ML', 'FinTech', 'SaaS'])"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(help_text='Your company website (without http://)', max_length=100),
        ),
    ]
