# Generated by Django 5.2.1 on 2025-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_add_featured_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpromotion',
            name='featured_order',
            field=models.PositiveIntegerField(default=999, help_text='Order for featured sections (lower numbers appear first, 0 = highest priority)'),
        ),
    ]
