# Generated by Django 5.2.1 on 2025-07-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_add_featured_order_to_partner_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpromotion',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured deal (maximum 4 deals can be featured at once)'),
        ),
    ]
