# Generated by Django 5.2.1 on 2025-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bid_submitted', 'New Bid Submitted'), ('bid_updated', 'Bid Status Updated'), ('pilot_updated', 'Pilot Updated'), ('payment_received', 'Payment Received'), ('pilot_pending_approval', 'Pilot Pending Approval'), ('admin_pilot_verification', 'Admin Pilot Verification'), ('pilot_approved', 'Pilot Approved'), ('pilot_rejected', 'Pilot Rejected'), ('bid_live', 'Bid Live'), ('completion_requested', 'Completion Requested'), ('completion_verified', 'Completion Verified')], max_length=25),
        ),
    ]
