# Generated by Django 5.2.1 on 2025-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bid_submitted', 'New Bid Submitted'), ('bid_under_review', 'Bid Under Review'), ('bid_approved', 'Bid Approved'), ('bid_live', 'Bid Live - Work Started'), ('bid_declined', 'Bid Declined'), ('bid_withdrawn', 'Bid Withdrawn'), ('completion_requested', 'Completion Requested'), ('completion_verified', 'Completion Verified'), ('work_completed', 'Work Completed'), ('pilot_pending_approval', 'Pilot Pending Approval'), ('pilot_approved', 'Pilot Approved'), ('pilot_rejected', 'Pilot Rejected'), ('pilot_updated', 'Pilot Updated'), ('payment_received', 'Payment Received'), ('admin_pilot_verification', 'Admin Pilot Verification'), ('admin_action_required', 'Admin Action Required')], max_length=50),
        ),
    ]
